name: CI

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  call:
    uses: gui-sc/ci-templates/.github/workflows/node-ts-docker.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}